// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IngSw_Bdd.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ModeloDeUrgenciasFeature : object, Xunit.IClassFixture<ModeloDeUrgenciasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Modelo de Urgencias", "    Esta feature esta relacionada al registro de ingresos de pacientes en la sala" +
                " \r\n    de urgencias respetando su nivel de preioridad y el horario de llegada.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ModuloUrgencias.feature"
#line hidden
        
        public ModeloDeUrgenciasFeature(ModeloDeUrgenciasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Id",
                        "Name",
                        "LastName"});
            table1.AddRow(new string[] {
                        "2D7E2179-254D-4634-9655-56345F27A339",
                        "Melisa",
                        "Rios"});
#line 6
 await testRunner.GivenAsync("que la siguiente enfermera esta registrada:", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso del primer paciente a la lista de espera de urgencias")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso del primer paciente a la lista de espera de urgencias")]
        public async System.Threading.Tasks.Task IngresoDelPrimerPacienteALaListaDeEsperaDeUrgencias()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso del primer paciente a la lista de espera de urgencias", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "SocialWork"});
                table2.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Perez",
                            "Maria",
                            "Swiss Medical"});
                table2.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Gomez",
                            "Ana",
                            "Galeno"});
#line 11
 await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table2, "Given ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table3.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Tiene gripe",
                            "EMERGENCY",
                            "38",
                            "70",
                            "15",
                            "120/80"});
#line 15
 await testRunner.WhenAsync("ingreso a urgencias al siguiente paciente:", ((string)(null)), table3, "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table4.AddRow(new string[] {
                            "20-45625563-9"});
#line 18
 await testRunner.ThenAsync("La lista de espera esta ordenada por cuil de la siguiente manera:", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente sin registro previo a la lista de espera de urgencias")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente sin registro previo a la lista de espera de urgencias")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteSinRegistroPrevioALaListaDeEsperaDeUrgencias()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente sin registro previo a la lista de espera de urgencias", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 23
 await testRunner.GivenAsync("que no existe el paciente registrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name"});
                table5.AddRow(new string[] {
                            "b4496ccd-1661-48ff-90e9-1432055e0226",
                            "Swiss Medical"});
                table5.AddRow(new string[] {
                            "abd31a2d-50d9-4b80-87ee-3dfeeae123ba",
                            "Galeno"});
#line 24
 await testRunner.AndAsync("que estan registradas las siguientes obras sociales:", ((string)(null)), table5, "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "Email",
                            "Phone",
                            "BirthDate",
                            "Street",
                            "Number",
                            "Locality",
                            "AffiliateNumber",
                            "IdSocialWork"});
                table6.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-4",
                            "Auchana",
                            "Leonel",
                            "leonel.auchana@mail.com",
                            "3814552211",
                            "1995-04-12",
                            "San Martín",
                            "452",
                            "San Miguel",
                            "4854166",
                            "b4496ccd-1661-48ff-90e9-1432055e0226"});
#line 28
 await testRunner.WhenAsync("registro al paciente a urgencias con los siguientes datos:", ((string)(null)), table6, "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table7.AddRow(new string[] {
                            "20-45625563-4",
                            "Tiene fiebre",
                            "EMERGENCY",
                            "39",
                            "70",
                            "15",
                            "120/80"});
#line 31
 await testRunner.AndAsync("ingreso a urgencias el nuevo paciente registrado:", ((string)(null)), table7, "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table8.AddRow(new string[] {
                            "20-45625563-4"});
#line 34
 await testRunner.ThenAsync("La lista de espera esta ordenada por cuil de la siguiente manera:", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente con datos mandatorios faltantes")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente con datos mandatorios faltantes")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteConDatosMandatoriosFaltantes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente con datos mandatorios faltantes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "SocialWork"});
                table9.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Perez",
                            "Maria",
                            "Swiss Medical"});
                table9.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Gomez",
                            "Ana",
                            "Galeno"});
#line 39
 await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table9, "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table10.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Tiene gripe",
                            "",
                            "38",
                            "70",
                            "15",
                            "120/80"});
#line 44
 await testRunner.WhenAsync("ingreso a urgencias al siguiente paciente:", ((string)(null)), table10, "When ");
#line hidden
#line 47
 await testRunner.ThenAsync("se informa la falta del dato mandatario \"El nivel de emergencia es requerido.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table11.AddRow(new string[] {
                            "20-45625563-9"});
#line 48
 await testRunner.AndAsync("La lista de espera no contendrá el cuil:", ((string)(null)), table11, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente frecuencia respiratoria negativa")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente frecuencia respiratoria negativa")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteFrecuenciaRespiratoriaNegativa()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente frecuencia respiratoria negativa", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "SocialWork"});
                table12.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Perez",
                            "Maria",
                            "Swiss Medical"});
                table12.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Gomez",
                            "Ana",
                            "Galeno"});
#line 53
 await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table12, "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table13.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Tiene gripe",
                            "EMERGENCY",
                            "38",
                            "70",
                            "-15",
                            "120/80"});
#line 57
 await testRunner.WhenAsync("ingreso a urgencias al siguiente paciente:", ((string)(null)), table13, "When ");
#line hidden
#line 60
 await testRunner.ThenAsync("se informa que la frecuencia respiratorio se cargo de forma incorrecta \"La frecue" +
                        "ncia respiratoria no puede ser un valor negativo ni igual a cero.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table14.AddRow(new string[] {
                            "20-45625563-9"});
#line 61
 await testRunner.AndAsync("La lista de espera no contendrá el cuil:", ((string)(null)), table14, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente con nivel de emergencia mayor a otro paciente ya en la lis" +
            "ta de espera")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente con nivel de emergencia mayor a otro paciente ya en la lis" +
            "ta de espera")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteConNivelDeEmergenciaMayorAOtroPacienteYaEnLaListaDeEspera()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente con nivel de emergencia mayor a otro paciente ya en la lis" +
                    "ta de espera", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "SocialWork"});
                table15.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Perez",
                            "Maria",
                            "Swiss Medical"});
                table15.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Gomez",
                            "Ana",
                            "Galeno"});
                table15.AddRow(new string[] {
                            "e927b2b1-a878-42dc-8f75-33139bcd7197",
                            "20-45625777-4",
                            "Auchana",
                            "Leonel",
                            "OSDE"});
#line 66
 await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table15, "Given ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table16.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Fiebre",
                            "EMERGENCY",
                            "39",
                            "71",
                            "16",
                            "120/80"});
                table16.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Dolor de ojo",
                            "URGENCY",
                            "38",
                            "71",
                            "16",
                            "120/80"});
#line 71
 await testRunner.AndAsync("que la lista de espera actual ordenada por nivel es:", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table17.AddRow(new string[] {
                            "e927b2b1-a878-42dc-8f75-33139bcd7197",
                            "20-45625777-4",
                            "apuñalada",
                            "CRITICAL",
                            "38",
                            "70",
                            "15",
                            "120/80"});
#line 75
 await testRunner.WhenAsync("ingreso a urgencias al siguiente paciente:", ((string)(null)), table17, "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table18.AddRow(new string[] {
                            "20-45625777-4"});
                table18.AddRow(new string[] {
                            "20-45625563-3"});
                table18.AddRow(new string[] {
                            "20-45625563-9"});
#line 78
 await testRunner.ThenAsync("La lista de espera esta ordenada por cuil considerando la prioridad de la siguien" +
                        "te manera:", ((string)(null)), table18, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente con nivel de emergencia menor a otro paciente ya en la lis" +
            "ta de espera")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente con nivel de emergencia menor a otro paciente ya en la lis" +
            "ta de espera")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteConNivelDeEmergenciaMenorAOtroPacienteYaEnLaListaDeEspera()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente con nivel de emergencia menor a otro paciente ya en la lis" +
                    "ta de espera", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "SocialWork"});
                table19.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Perez",
                            "Maria",
                            "Swiss Medical"});
                table19.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Gomez",
                            "Ana",
                            "Galeno"});
                table19.AddRow(new string[] {
                            "e927b2b1-a878-42dc-8f75-33139bcd7197",
                            "20-45625777-4",
                            "Auchana",
                            "Leonel",
                            "OSDE"});
#line 85
 await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table19, "Given ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table20.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Fiebre",
                            "EMERGENCY",
                            "39",
                            "71",
                            "16",
                            "120/80"});
#line 90
 await testRunner.AndAsync("que la lista de espera actual ordenada por nivel es:", ((string)(null)), table20, "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table21.AddRow(new string[] {
                            "e927b2b1-a878-42dc-8f75-33139bcd7197",
                            "20-45625777-4",
                            "apuñalada",
                            "URGENCY",
                            "38",
                            "70",
                            "15",
                            "120/80"});
#line 93
 await testRunner.WhenAsync("ingreso a urgencias al siguiente paciente:", ((string)(null)), table21, "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table22.AddRow(new string[] {
                            "20-45625563-3"});
                table22.AddRow(new string[] {
                            "20-45625777-4"});
#line 96
 await testRunner.ThenAsync("La lista de espera esta ordenada por cuil considerando la prioridad de la siguien" +
                        "te manera:", ((string)(null)), table22, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ingreso de un paciente con el mismo nivel de emergencia que otro paciente ya en l" +
            "a lista de espera")]
        [Xunit.TraitAttribute("FeatureTitle", "Modelo de Urgencias")]
        [Xunit.TraitAttribute("Description", "Ingreso de un paciente con el mismo nivel de emergencia que otro paciente ya en l" +
            "a lista de espera")]
        public async System.Threading.Tasks.Task IngresoDeUnPacienteConElMismoNivelDeEmergenciaQueOtroPacienteYaEnLaListaDeEspera()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso de un paciente con el mismo nivel de emergencia que otro paciente ya en l" +
                    "a lista de espera", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "LastName",
                            "Name",
                            "SocialWork"});
                table23.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Perez",
                            "Maria",
                            "Swiss Medical"});
                table23.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Gomez",
                            "Ana",
                            "Galeno"});
                table23.AddRow(new string[] {
                            "e927b2b1-a878-42dc-8f75-33139bcd7197",
                            "20-45625777-4",
                            "Auchana",
                            "Leonel",
                            "OSDE"});
#line 102
 await testRunner.GivenAsync("que estan registrados los siguientes pacientes:", ((string)(null)), table23, "Given ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table24.AddRow(new string[] {
                            "146d0ee4-20f2-451f-b46e-09ef98568bab",
                            "20-45625563-3",
                            "Fiebre",
                            "CRITICAL",
                            "39",
                            "71",
                            "16",
                            "120/80"});
                table24.AddRow(new string[] {
                            "26cf78de-7511-4a94-a466-af8c18927159",
                            "20-45625563-9",
                            "Dolor de ojo",
                            "URGENCY",
                            "38",
                            "71",
                            "16",
                            "120/80"});
#line 107
 await testRunner.AndAsync("que la lista de espera actual ordenada por nivel es:", ((string)(null)), table24, "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Cuil",
                            "Informe",
                            "Nivel de Emergencia",
                            "Temperatura",
                            "Frecuencia Cardiaca",
                            "Frecuencia Respiratoria",
                            "Tension Arterial"});
                table25.AddRow(new string[] {
                            "e927b2b1-a878-42dc-8f75-33139bcd7197",
                            "20-45625777-4",
                            "apuñalada",
                            "CRITICAL",
                            "38",
                            "70",
                            "15",
                            "120/80"});
#line 111
 await testRunner.WhenAsync("ingreso a urgencias al siguiente paciente:", ((string)(null)), table25, "When ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "Cuil"});
                table26.AddRow(new string[] {
                            "20-45625563-3"});
                table26.AddRow(new string[] {
                            "20-45625777-4"});
                table26.AddRow(new string[] {
                            "20-45625563-9"});
#line 114
 await testRunner.ThenAsync("La lista de espera esta ordenada por cuil considerando la prioridad de la siguien" +
                        "te manera:", ((string)(null)), table26, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ModeloDeUrgenciasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ModeloDeUrgenciasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
